<a href="https://colab.research.google.com/github/ismoil27/ai_foundation/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)

arr.shape

numpy_array: [1 3 5 7]


(4,)

In [ ]:
arr2 = np.array([[1, 3, 5, 7], [4, 6, 8, 9]])
print('numpy_array2:', arr2)

arr2.shape

numpy_array2: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [ ]:
# dtype()
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [ ]:
# reshape()
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print("shaped_array:", b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [ ]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print("float:", b)

float: [1. 2. 3.]


In [ ]:
# np.zeros(), np.ones() => dummy data
z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print("ones:", o)


zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# ndim
a = np.array([[1, 2], [3, 4]])
print("ndim:", a.ndim)

ndim: 2


In [ ]:
# arange()
a = np.arange(1, 7)
print("arange:", a)

arange: [1 2 3 4 5 6]


In [ ]:
# sum(), mean(), max(), min()

a = np.array([1, 2, 3, 4])

print("sum:", a.sum())
print("mean:", a.mean())
print("max:", a.max())
print("min:", a.min())

sum: 10
mean: 2.5
max: 4
min: 1


In [ ]:
# flatten()

a = np.array([[1, 2], [3, 4]])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [ ]:
# T (Transpose)
a = np.array([[1, 2], [3, 4]])
print("transpose:", a.T)

transpose: [[1 3]
 [2 4]]


In [ ]:
# dot() @
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print("dot/multiplication:", a.dot(b))

dot/multiplication: [[ 4  4]
 [10  8]]


In [ ]:
# random.rand()
a = np.random.rand(2, 3) # => 0.0 and 1.0 / 0.0 included / 1.0 excluded
print("random rand:", a)

random rand: [[0.86089698 0.01400655 0.14365008]
 [0.81635541 0.8480843  0.74890138]]
